name: sampling
description: |
  Various algorithms for selection of a subset (a statistical sample) of individuals from within
  a statistical population to estimate characteristics of the whole population.
version: 1.1.1
homepage: https://github.com/isoos/sampling
topics:
  - reservoir
  - statistics

environment:
  sdk: '^3.0.0'

#dependencies:

dev_dependencies:
  test: ^1.3.0
  lints: ^4.0.0
